# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tastewith' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for tastewith
    pod 'Firebase/AdMob'
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Crash'
    pod 'Firebase/Database'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Firestore'
    pod 'Firebase/Invites'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'
    pod 'Firebase/Performance'
end
